### ISSUE TITLE
Temperature is wrong displayed

### ISSUE THREAD

**Issue by axute** [rowysock/home-assistant-HomeWhiz#1]
![image](https://user-images.githubusercontent.com/641986/187166814-d1a4c8a8-6df3-41a9-8336-e7f78457ac24.png)
The temperature is actually set at 40°, but 168° is displayed.

By the way, the extension itself is very good.

**Comment by AlxVasilchenko** [comment]
I support the previous speaker. I express respect to the author of the integration.

**Comment by rowysock** [comment]
Sometimes a value of 128 is added to the temperature or spin during the washing cycle. It seems to be some kind of program override. I couldn't figure out what it means exactly. Simply subtracting 128 seems to be working.

A new version should be available in HACS
