### ISSUE TITLE
AC’s integration 

### ISSUE THREAD

**Issue by 999delights** [rowysock/home-assistant-HomeWhiz#101]
![325B881E-6DB4-48FE-8F4C-0B440AA07804](https://user-images.githubusercontent.com/82140288/215316590-0df19525-51b5-4d54-bebc-e14cb4d8e059.jpeg)
![82EEAD4E-22A8-4011-ACC4-F8AB652A002C](https://user-images.githubusercontent.com/82140288/215316594-d0d47cfc-ea52-412c-8c6a-20cf2b1f2175.jpeg)
![73D91A48-1DB8-48CB-BFD3-67AF362C237E](https://user-images.githubusercontent.com/82140288/215316595-3b6ab2e6-8417-4ad0-8cce-502af2091a4a.jpeg)
 i added my AC’s but i cant access them

**Comment by TechHummel** [comment]
Please provide more details like logs, Ids etc. You can also refer to the readme file.
