### ISSUE TITLE
[org.bluez.Error.Failed] Software caused connection abort

### ISSUE THREAD

**Issue by EinSchwerd** [rowysock/home-assistant-HomeWhiz#11]
I've installed the custom integration. I'm running HA on a NUC with integrated bluetooth adapter that has the bluetooth integration installed in HA.
All entities on the 1 device on the HomeWhiz itegration are Unavailable and I'm getting the following error in the log:

> This error originated from a custom integration.
>
> Logger: custom_components.HomeWhiz
> Source: custom_components/HomeWhiz/__init__.py:50
> Integration: HomeWhiz (documentation, issues)
> First occurred: 08:47:28 (1887 occurrences)
> Last logged: 10:04:31
>
> [org.bluez.Error.Failed] Software caused connection abort

Any suggestions how to work around this issue?

Note that the washing machine should be in range of the HA server as I do see the machine on my mobile phone sitting next to the NUC.

**Comment by mf1x** [comment]
I am having the same problem. HomWhiz detects the device and eight entities but all of them are unavailable.

**Comment by pax0r** [comment]
I have same issue on RPi built-in bluetooth. Does this mean built-in bluetooth is too weak to get the signal? (In my case it's quite short distance, so I wonder how BAD is built-in bluetooth)

**Comment by mf1x** [comment]
Mh... Not sure... As I said, I use a USB BT 5.0 adapter with an extension cable and it's only a couple of metres from the washing machine. It's able to pick up the appliance when I set up the integration. It's also updating the entities when I restart HA. It's not updating when I start a cycle and leave Home Assistant running.

I am also too stupid to find the logs at the moment. lol...

**Comment by TechHummel** [comment]
Could you retry with the latest version in the main branch as Bluetooth handling got improved?
