### ISSUE TITLE
States and sensors not fully "translated" 

### ISSUE THREAD

**Issue by Mikescotland** [rowysock/home-assistant-HomeWhiz#111]
Hi. I have a beko washer dryer and I can see that despite translation "en" some states and switches have "non translated" values (see screenshot), also "DEVICE_STATE_OFF" etc. 
![Screenshot_20230228_161426_io homeassistant companion android]
(https://user-images.githubusercontent.com/52081323/221914713-dfa7226b-094a-4eed-a286-d3e61c7d0549.jpg)

**Comment by TechHummel** [comment]
Hi and thanks for creating an issue! 👋
This issue is already dressed in #100 but not merged or available in a new release yet.
