### ISSUE TITLE
Strugging to get washer to see bluetooth

### ISSUE THREAD

**Issue by Rowleys** [rowysock/home-assistant-HomeWhiz#112]
Hi, I have all setup but when I click on HomeWhiz and then click Bluetooth I get an error saying "No devices found on the network"

When I add through the cloud it all shows but it all shows "Unavailable" 

Thanks

**Comment by TechHummel** [comment]
Have you added the Bluetooth integration and is your home assistant running device Bluetooth capable?
Can you ensure that your washer is in range and does it have Bluetooth enabled

**Comment by Rowleys** [comment]
I think I need to do a range test. Does the Bluetooth in HA talk to anything in the iPhone

**Comment by TechHummel** [comment]
Not sure!
