### ISSUE TITLE
Home assistant won't refresh sensor value until you open the homewhiz app on phone

### ISSUE THREAD

**Issue by jyavenard** [rowysock/home-assistant-HomeWhiz#128]
With my Beko dryer with Homewhiz support, added HACS integration.

When the dryer has been running for a while say 20 minutes, Home Assistant will show the time remaining values as it was last checked. 20 minutes ago.

Open the Homewhiz app, which has soon as it connects to the device and show the updated remaining time: only then will home assistant also shown the proper remaining time...

Another way to force the sensors value to be refreshed is to reload the integration.

**Comment by macicek86** [comment]
See #126 
 https://github.com/rowysock/home-assistant-HomeWhiz/issues/126

**Comment by TechHummel** [comment]
Thanks @macicek86 👍

**Comment by jyavenard** [comment]
I updated to main branch. And the issue still occurs. It will not update until I go into the whiz app.
