### ISSUE TITLE
Feature request: Bypass app connection

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [rowysock/home-assistant-HomeWhiz#13]
Is there any chance to support setting up the integration without having to use the HomeWhiz application?

The app doesn't work if your phone is rooted, and I'm not a big fan of un-rooting (even temporarily) or getting an un-rooted phone. Without connection HomeAssistant recognize the device (even through Bluetooth proxy) but the states stay on Unavailable.

**Comment by rowysock** [comment]
If the integration is able to detect your appliance, but the states stay on Unavailable, either your model is not yet supported, or you have some connectivity problem. Can you share your logs?

**Comment by TechHummel** [comment]
What would we need for bypassing the app connection? Traced Bluetooth traffic between app and appliance?

**Comment by rowysock** [comment]
Currently, we need the user's HomeWhiz account to fetch the appliance configuration (mapping file) and the entity name translations.

**Comment by TechHummel** [comment]
Yes! But I thought that the app was still needed to initiate the connection somehow (Readme, Configuration Step 1 and 2)?

**Comment by rowysock** [comment]
I've added those steps only to ensure that users are able to connect with the appliance at least with the original app. To have this basic level of certainty when something goes wrong. The appliance configured in the original app is not technically required (for the BT appliances), but the HomwWhiz account still is.

**Comment by GeoffreyFrogeye** [comment]
> If the integration is able to detect your appliance, but the states stay on Unavailable, either your model is not yet supported, or you have some connectivity problem. Can you share your logs?

I wanted to reproduce the setup on a clean Home Assistant installation and with a proper bluetooth adapter so I could share logs, but I wasn't able to.

Instead I tried borrowing a friend's phone to do the connection to the app, and the very same setup that didn't work started working. I could even upgrade to the latest integration version – and it works very well, I'm happy.

I also noticed (but could be a mind trick) that the Bluetooth icon on the device started blinking more often, even when Home Assistant was down. This is pure speculation, but maybe connecting the device to the app permanently changes a setting on the device that allows proper information transmission?

I should probably have at least shared my device: Beko WTV8716XBWST (appears as 7149345500 in Home Assistant).

**Comment by rowysock** [comment]
@GeoffreyFrogeye glad to hear that the integration is working for you!

Hard to tell how the original app pairs with the device and what's happening after. 
As a side note: the original app requires the pairing mode (hold the specific button combination for 3 seconds) to pair properly, while this integration has no problem pairing even without pairing mode. Hard to tell why
