### ISSUE TITLE
Future: Deprecated functionality

### ISSUE THREAD

**Issue by znanywawa** [rowysock/home-assistant-HomeWhiz#131]
At newest version of Home Assistant, there is new log entry:
`WARNING (MainThread) [py.warnings] /config/custom_components/homewhiz/bluetooth.py:54: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead
  _LOGGER.info(f"Successfully connected. RSSI: {self._device.rssi}")
`

So seems that this is something that should be considered (just pointing it out).

**Comment by TTLucian** [comment]
Same
```This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/homewhiz/bluetooth.py:54
Integration: HomeWhiz (documentation, issues)
First occurred: 18:54:07 (1 occurrences)
Last logged: 18:54:07

/config/custom_components/homewhiz/bluetooth.py:54: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead _LOGGER.info(f"Successfully connected. RSSI: {self._device.rssi}")```
