### ISSUE TITLE
Washing machine becomes unavailable

### ISSUE THREAD

**Issue by alhemicar86** [rowysock/home-assistant-HomeWhiz#134]
Every time, after several hours, up to a few days, the washing machine entities become unavailable, and remain like that until removed and added again. Machine remains connected to home assistant all the time.

**Comment by TechHummel** [comment]
Hi 👋 
for troubleshooting, I would need logs, please.

**Comment by alhemicar86** [comment]
I think I accidentally resolved the issue. It had to do with HA allowing integrations to add space at the end of entity name. I had one entity with space at the end (not related to this integration, it originated from core HA integrations), and it caused this and one more custom integration to go from unavailable to stuck states. Had nothing in logs, but will keep an eye if things go unavailable again, or something pops up. But so far it seems that everything works, and the random "illegal" entity name caused it.

**Comment by TechHummel** [comment]
Thanks for your feedback. I'll close the issue for now!
