### ISSUE TITLE
Use lowercase domain name in manifest

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#14]
The domain name in the manifest needs to be in lowercase. This is currently blocking adding the HomeWhiz logo to HomeAssistant.
https://github.com/home-assistant/brands/pull/3655

**Comment by rowysock** [comment]
I will change it in a second

**Comment by rowysock** [comment]
Fixed by 232307576e30683523beaca81f611e185c08dd09
