### ISSUE TITLE
Logging warning after update on HA 2023.8

### ISSUE THREAD

**Issue by dula34** [rowysock/home-assistant-HomeWhiz#148]
/config/custom_components/homewhiz/bluetooth.py:54: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead _LOGGER.info(f"Successfully connected. RSSI: {self._device.rssi}")

**Comment by TechHummel** [comment]
Duplicate of #131
