### ISSUE TITLE
Beko washer with dryer 

### ISSUE THREAD

**Issue by StarvingDeveloper** [rowysock/home-assistant-HomeWhiz#16]
Awesome plugin and everything went fine until dryer phase - I have Beko HTE 7616 X0 and when drying phase started sub-state become UNKNOW.

I checked your code and can see only 20 sub-state defined. How I could sniffer drying related sub-states.?

![Untitled](https://user-images.githubusercontent.com/20921424/202159792-d6e000a4-54b8-49b1-8a3e-a6e5d39f7b93.png)

**Comment by StarvingDeveloper** [comment]
Actually plugin got stuck at this state and helped only HA restart.
But still when  washer turned off show some strange info.
![Untitled](https://user-images.githubusercontent.com/20921424/201698353-61ae350b-7cea-45a5-96a1-bb28152b9497.png)

**Comment by TechHummel** [comment]
Instead of sniffing, you could also try to log the data of your dryer within homeassistant.
E.g., by adding a logging command here https://github.com/rowysock/home-assistant-HomeWhiz/blob/main/custom_components/HomeWhiz/homewhiz.py#L82 .
```python
_LOGGER = logging.getLogger(__name__)
_LOGGER.warning(message)
```

**Comment by StarvingDeveloper** [comment]
@TechHummel for now I have bigger problem - after drying session addon get stuck every time on REMOVE LAUNDRY and I must remove and add it again to get it working.

**Comment by mf1x** [comment]
Same here with my washing machine. When a wash has finished Home Assistant crashes and restarts after a couple of minutes.

**Comment by StarvingDeveloper** [comment]
@rowysock any thoughts why homewiz addon stops responding to HA, or as for some even crash HA?

**Comment by TechHummel** [comment]
Nothing in the logs?

**Comment by StarvingDeveloper** [comment]
ok, I think I found why homewhiz crash whole HA

```
This error originated from a custom integration.
Logger: custom_components.HomeWhiz
Source: custom_components/HomeWhiz/__init__.py:50
Integration: HomeWhiz (documentation, issues)
First occurred: 17 November 2022 at 21:36:15 (3462 occurrences)
Last logged: 08:12:06
```
and if I understand right homewhiz trying connect to washer non stop at that line:
https://github.com/rowysock/home-assistant-HomeWhiz/blob/5e3bf925bce84b50f8d825e2c25c6cba8b2da54f/custom_components/HomeWhiz/__init__.py#L50

but my washer dont have power most the time, so cant respond and after awhile homewhizh crash whole HA.

Anybody familiar with python and HA could improve that part of the code?

**Comment by TechHummel** [comment]
Maybe using this https://github.com/Bluetooth-Devices/bleak-retry-connector might help too.

**Comment by StarvingDeveloper** [comment]
@TechHummel tnx for help - I managed to find DRYING value are 21 and made pull request:
https://github.com/rowysock/home-assistant-HomeWhiz/pull/19

As for crashing issue I just increased sleep time to 60 seconds so HomeWhiz wont drop 86400 warnings every day if your washing machine outside rage for whatever reason. That only temporally solution till @rowysokc respond what he things about bleak retry or any other solution, but 80 thousand warnings everyday really bad idea. So far second day without crashing with sleep increase.

**Comment by TechHummel** [comment]
That makes sense to me, one second seems to be too much — Home Assistant does recommend [a timer of 10 seconds](https://developers.home-assistant.io/docs/bluetooth/).

Considering that @rowysock hasn't been active for two months and there are some open pull requests, maybe we should take this project over for now 🤔? We can always merge changes back later 👍
What do you think?

**Comment by rowysock** [comment]
Hi guys, sorry for being unresponsive for 2 months, had a lot on my head lately. 

I think it would be best for the users not to create multiple repositories. I've added @TechHummel as a collaborator.

As for drying value. The original app works as follows:
* Based on the appliance, it chooses one of the mapping files (I'm not sure how the decision is made)
* It uses the mapping file to decode the raw bytes from the appliance

I've recreated one of the mappings in this integration (the generic washing machine)

Adding value 21 as Drying to the current code differs from the original logic, but I cannot imagine it breaking anything, so we can add it temporarily. In the long run. I would like to recreate the logic from the app.

**Comment by rowysock** [comment]
Also, [bleak-retry-connector](https://github.com/Bluetooth-Devices/bleak-retry-connector) sounds like a great idea. I didn't know about it, or HA Bluetooth best practices. Thank you. I will try to use it

**Comment by TechHummel** [comment]
Thanks for coming back, very appreciated! 👋 
I do agree about the multiple repositories for sure, I'll open a pull request with my changes—and thanks for the honour of collaborating with me! 😄

**Comment by StarvingDeveloper** [comment]
Welcome back @rowysock!
> Based on the appliance, it chooses one of the mapping files

these mapping files can be found in .apk?

>Adding value 21 as Drying to the current code differs from the original logic, but I cannot imagine it breaking anything

then maybe worth add 1 more:  IDLE = 0


And for last, not releated, but why sudenly after awhile your addon lose mind and restore connection with washer only after HA restart?
```
2022-11-22 10:50:06.326 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/HomeWhiz/__init__.py", line 78, in reconnect
    await self.client.stop_notify("0000ac02-0000-1000-8000-00805f9b34fb")
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 667, in stop_notify
    await self._backend.stop_notify(char_specifier)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 917, in stop_notify
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] No notify session started
```

I still blame that [line 89 ](https://github.com/rowysock/home-assistant-HomeWhiz/blob/5e3bf925bce84b50f8d825e2c25c6cba8b2da54f/custom_components/HomeWhiz/__init__.py#L89), because while it was at 60 seconds homewhiz never crashed for a week. When I decreased value to 10 it started crash once a day.

**Comment by TechHummel** [comment]
Can you share how you modified your code?

**Comment by StarvingDeveloper** [comment]
> Can you share how you modified your code?
I just removed warning and increased time to 10 seconds.
```

            except Exception as e:
                _LOGGER.warning(e)
                await asyncio.sleep(1)
```

```
            except Exception as e:
                await asyncio.sleep(10)
```

**Comment by StarvingDeveloper** [comment]
> Can you share how you modified your code?

I just removed warning and increased time to 10 seconds in __init__.py
```

            except Exception as e:
                _LOGGER.warning(e)
                await asyncio.sleep(1)
```

```
            except Exception as e:
                await asyncio.sleep(10)
```
and add 2 line to homewhiz.py: IDLE = 0 and DRYING = 21. 

P.S. digging trough com.homewhiz.global_2022-11-16.apk\resources\assets found these mapping files.

**Comment by TechHummel** [comment]
Thanks! I do feel that logging a warning for a failed connection is appropriate - I personally don't have that many log entries. As a workaround, you could always reduce the log level for the homewhiz integration.
If you found those two entries within the apk, I personally think it makes sense to add them 👍

**Comment by StarvingDeveloper** [comment]
> If you found those two entries within the apk, I personally think it makes sense to add them +1

No, these values I found awhile ago by following your [advice](https://github.com/rowysock/home-assistant-HomeWhiz/issues/16?notification_referrer_id=NT_kwDOAT88ULM0ODMwMTM5MTc3OjIwOTIxNDI0#issuecomment-1317274179).

In mapping files I can see devices send much more info current integration version do not decode at all. So I just catch these 2 values in logs and that is enough info for me.

Also saw developing active moving on when you joined, so let me know if you need test something.

**Comment by TechHummel** [comment]
That makes sense! And thank you for your offer 👍

**Comment by StarvingDeveloper** [comment]
closing this issue since it got solved. tnx everyone who helped.
