### ISSUE TITLE
Changing entity name not working

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#27]
Followup of #5 

> > > I think it was because of me changing the entity names from mac adres to something human friendly
> > 
> > 
> > Can confirm - if you change the MAC to a human-readable value then it stops collecting data.
> > Re-adding means removing the Homewhiz integration and associated devices, restarting Home Assistant, and then adding back HomeWhiz.
> > For some reason if I try this without restarting Home Assistant then the HomeWhiz installer just offers me a blank dialogue box that I can only cancel out of.
> 
> this isue should get fixed or at least add to the description, so people wont change to human-readable value and wont get disappointed.

**Comment by TechHummel** [comment]
This is still behaving odd. When changing the device name, all entities are created again (with "_2" added to the entity name) but starting with the original device name and the old entities are shown as not provided anymore.

**Comment by rowysock** [comment]
Can you check if the issue still persiste again after the recent changes?

**Comment by TechHummel** [comment]
I checked and it is working now!
