### ISSUE TITLE
Change entity class of "State" and "Sub state" to enum

### ISSUE THREAD

**Issue by rowysock** [rowysock/home-assistant-HomeWhiz#37]
In the recent changes, Home Assistant introduced a new entity class: "enum". This class can specify all of the available options to be used in automation.
We should use this class for "State" and "Sub state" when this feature is available in the stable release

https://github.com/home-assistant/core/pull/82489
https://developers.home-assistant.io/docs/core/entity/sensor/#:~:text=system%20is%20metric.-,options,-list

**Comment by TechHummel** [comment]
Hopefully ENUM class will be part of 2013.01 😄

**Comment by frenck** [comment]
@TechHummel It is.
