### ISSUE TITLE
Documentation for (ongoing) Developers

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#41]
I did not manage to run pytest without renaming parser.py to test_parser.py and reverting afterwards...

As for the readme I wrote this https://github.com/maxx4096/home-assistant-HomeWhiz/blob/Documentation/linux_dev.md .

_Originally posted by @maxx4096 in https://github.com/rowysock/home-assistant-HomeWhiz/pull/35#discussion_r1039024715_

**Comment by maxx4096** [comment]
Are you OK with the file location or do we create a documentation folder for it. If yes I'll do a pull request.

**Comment by TechHummel** [comment]
I am personally fine with it 😄

**Comment by maxx4096** [comment]
#47 is live.

**Comment by TechHummel** [comment]
Closed by #47, thank you so much!
