### ISSUE TITLE
Fetch user appliance description from the API

### ISSUE THREAD

**Issue by rowysock** [rowysock/home-assistant-HomeWhiz#45]
We can fetch the user appliance description from the API. It contains a lot of specific device info like a model, brand, or serial number. It contains also the name under which it was configured in the HomeWhiz app. we could use this as a device name in HA instead of the ugly `HwZ_fb032dd767002b071c`

@TechHummel This is the last thing I would like to implement before releasing a new version

**Comment by TechHummel** [comment]
I was just about to ask you about your opinion on a new tagged version 😂

**Comment by rowysock** [comment]
I'm also eagerly waiting for the PR to HACS default repo :)
Maybe someday this integration will become an official HA component

Can you test the newest version on your machine? 

Also, I can't thank you enough for all the work you've put into this project <3

**Comment by TechHummel** [comment]
I hope I'll be able to test end of next week!

Adding an integration officially can be a lot of work. I tried that a while ago but didn't want to publish my code additionally as a python module on pypi. However, I'd be interested in going through the process again and actually succeed! 😁

Hardly any work compared to you! I actually wish I could be of more assistance and contribute actual code - hopefully soon!
