### ISSUE TITLE
feature request: making this work with the new "Bluetooth Proxy"

### ISSUE THREAD

**Issue by dpasman** [rowysock/home-assistant-HomeWhiz#5]
Works very well, tested it on my Raspberry Pi! But since I am using mainly a NUC like device without bluetooth. I would like to use the new "bluetooth proxy". (https://esphome.github.io/bluetooth-proxies/)

Would it be possible implementing this? Are there any plans on this already?

Once again, it works very well. Thanks for creating this!

**Comment by Kannix2005** [comment]
Hey,

I tried that and this doesn ´t really work in my opinion until ESPHome supports active connections. See PR https://github.com/rowysock/home-assistant-HomeWhiz/pull/4

Best
Stefan

**Comment by proffalken** [comment]
Can confirm that the proxy can see the machine, but won't connect to it, presumably for the reasons that @Kannix2005 mentions.

![image](https://user-images.githubusercontent.com/262545/190174871-61b122b3-0d13-4cb7-888a-fa5d14a20532.png)


Hopefully ESPHome will support active proxies soon and then we can get this working there too!

Thanks for the work so far, looking forward to being able to easily see how long is left on the wash without having to go into the garage!

**Comment by lasharor** [comment]
FYI Home assistant now supports Active connections. 

https://www.home-assistant.io/blog/2022/10/05/release-202210/#active-bluetooth-everywhere

**Comment by proffalken** [comment]
FWIW, I created a new remote-bluetooth-proxy using the active settings, restarted HA and my washing machine showed up automagically!

![image](https://user-images.githubusercontent.com/262545/194297385-bb8a1f08-8136-416d-bc13-63d3694732e1.png)

Haven't tested it with a full cycle yet, but I can see all the sensors I'd expect to see!

**Comment by dpasman** [comment]
Can confirm, works like a charm!

**Comment by dpasman** [comment]
After some more testing I came to conclusion that the washing machine indeed shows up automatically when restarting home assistant.

But whenever you restart home-assistant again, it looks like the device is not reconnecting.

Following warning is given from homeassistant: `This entity is no longer being provided by the HomeWhiz integration. If the entity is no longer in use, delete it in settings.`

Perhaps it is needing some more time to come back up (for now I waited around 10 minutes).

**Comment by proffalken** [comment]
> I think it was because of me changing the entity names from mac adres to something human friendly

Can confirm - if you change the MAC to a human-readable value then it stops collecting data.

Re-adding means removing the Homewhiz integration and associated devices, restarting Home Assistant, and then adding back HomeWhiz.

For some reason if I try this without restarting Home Assistant then the HomeWhiz installer just offers me a blank dialogue box that I can only cancel out of.

**Comment by StarvingDeveloper** [comment]
> > I think it was because of me changing the entity names from mac adres to something human friendly
> 
> Can confirm - if you change the MAC to a human-readable value then it stops collecting data.
> 
> Re-adding means removing the Homewhiz integration and associated devices, restarting Home Assistant, and then adding back HomeWhiz.
> 
> For some reason if I try this without restarting Home Assistant then the HomeWhiz installer just offers me a blank dialogue box that I can only cancel out of.

this isue should get fixed or at least add to the description, so people wont change to human-readable value and wont get disappointed.

**Comment by TechHummel** [comment]
Since BT proxy is working now, I'll close this issue 👍
