### ISSUE TITLE
HomeWhiz is not detecting any products in the house

### ISSUE THREAD

**Issue by adriangurbina** [rowysock/home-assistant-HomeWhiz#55]
Hello,
I have a Beko washing machine connected to HomeWhiz android app.
The Addon is not able to detect any devices from HomeWhiz.

Best regards,
Adrian

**Comment by TechHummel** [comment]
Did you add the Bluetooth integration to homeassistant?

**Comment by rowysock** [comment]
It's probably a matter of range. In my case, the max distance between the washing machine and the laptop running HA is only 5-10 meters.

**Comment by adriangurbina** [comment]
thank you fixed.
