### ISSUE TITLE
Default entity names are wrong

### ISSUE THREAD

**Issue by jmav** [rowysock/home-assistant-HomeWhiz#58]
When devices are added by default name is e.g.: for state -> sensor.state, it should be sensor.{{devicename}}_state.
When renaming the the device, this should automatically be replaced with new device name.

![rename](https://user-images.githubusercontent.com/140089/207210409-a79afa16-c560-48ac-800d-7095273dba7f.png)
![entity](https://user-images.githubusercontent.com/140089/207210416-58a89ee0-87fe-4195-a625-ea763e01edad.png)

**Comment by rowysock** [comment]
@TechHummel would you like to look into that?

Also, I think this is related https://developers.home-assistant.io/docs/core/entity/#entity-naming

**Comment by TechHummel** [comment]
I will!
