### ISSUE TITLE
Unsupported machine?

### ISSUE THREAD

**Issue by Sirse** [rowysock/home-assistant-HomeWhiz#7]
![изображение](https://user-images.githubusercontent.com/3335371/190675241-7c706152-ed30-434d-82f9-7ef68537ccc3.png)

![изображение](https://user-images.githubusercontent.com/3335371/190677425-9725208d-9f84-4f62-b406-dcfc9e6f5372.png)

Model: BEKO WDB 7425 R2W

**Comment by rowysock** [comment]
I can't easily verify if your model is supported, but the error doesn't indicate that. 

A similar problem was described here: https://github.com/hbldh/bleak/issues/631
From what I understand the problem is just an unreliable connection.
