### ISSUE TITLE
Support for advanced AC features

### ISSUE THREAD

**Issue by rowysock** [rowysock/home-assistant-HomeWhiz#71]
Add support for:
* AIR_CONDITIONER_MODE_DEHUMIDIFICATION
* AIR_CONDITIONER_JET_MODE
* AIR_CONDITIONER_SOFT_AIR
* AIR_CONDITIONER_UP_DOWN_VANE_CONTROL
* AIR_CONDITIONER_LEFT_RIGHT_VANE_CONTROL
* AIR_CONDITIONER_SLEEP_MODE
* AIR_CONDITIONER_AUTO_SWITCH_ON
* AIR_CONDITIONER_AUTO_SWITCH_OFF
* AIR_CONDITIONER_INSTANT_CONSUMPTION

**Comment by rowysock** [comment]
@tnrclkr I'm going to need your help with that

**Comment by tnrclkr** [comment]
@rowysock Details in your mailbox. Thanks for all your support.

**Comment by tnrclkr** [comment]
Thats a surprise but :) all looks working now for the air conditioner

![AC1](https://user-images.githubusercontent.com/48097971/210074523-c0ca3ec0-e827-48cf-a1e3-299fcee5619f.JPG)

**Comment by tnrclkr** [comment]
TURN ON / OFF
set temperature
set mode
set fan speed

**Comment by rowysock** [comment]
That's interesting because I've logged into your account, and for me, Climate entity is unavailable because integration fails to map the fan mode

**Comment by tnrclkr** [comment]
Only change i made on HASS is deleted all widgets and integrations and installed with a new password. Added over cloud. thats all. works great now.

**Comment by rowysock** [comment]
I'm trying to figure out how to implement Swing modes. In HA there's only a limited number of options when it comes to swing modes (https://developers.home-assistant.io/docs/core/entity/climate#swing-modes):
* SWING_OFF
* SWING_ON
* SWING_VERTICAL
* SWING_HORIZONTAL
* SWING_BOTH

However, I see that your AC has much more control over the swinging in both directions. 

```
 'UP_DOWN_VANE_CONTROL_1': '1',
 'UP_DOWN_VANE_CONTROL_2': '2',
 'UP_DOWN_VANE_CONTROL_3': '3',
 'UP_DOWN_VANE_CONTROL_4': '4',
 'UP_DOWN_VANE_CONTROL_5': '5',
 'UP_DOWN_VANE_CONTROL_6': '6',
 'UP_DOWN_VANE_CONTROL_AUTO': 'Auto',
 'UP_DOWN_VANE_CONTROL_OFF': 'Off',
 
 'LEFT_RIGHT_VANE_CONTROL_1': '1',
 'LEFT_RIGHT_VANE_CONTROL_2': '2',
 'LEFT_RIGHT_VANE_CONTROL_3': '3',
 'LEFT_RIGHT_VANE_CONTROL_4': '4',
 'LEFT_RIGHT_VANE_CONTROL_5': '5',
 'LEFT_RIGHT_VANE_CONTROL_AUTO': 'Auto',
 'LEFT_RIGHT_VANE_CONTROL_LEFT': 'Left',
 'LEFT_RIGHT_VANE_CONTROL_OFF': 'Off',
 'LEFT_RIGHT_VANE_CONTROL_RIGHT': 'Right',
 ```

We have two options:  
* Map the VANE_CONTROL HomeWhiz options to SWING_MODE Home Assistant options
* Implement the VANE_CONTROL, not as a part of HA Climate entity, but as a separate Select entity 

What do you think?

**Comment by rowysock** [comment]
> TURN ON / OFF
> set temperature
> set mode
> set fan speed

Those are the features you tested that are working?
I'm pretty sure that the fan speed should not be working for your AC.

**Comment by tnrclkr** [comment]
ım not at home atm, will be there within 1hr then ill test all modes to inform you in detail.

**Comment by TechHummel** [comment]
> We have two options:
> 
> * Map the VANE_CONTROL HomeWhiz options to SWING_MODE Home Assistant options
> * Implement the VANE_CONTROL, not as a part of HA Climate entity, but as a separate Select entity
> 
> What do you think?

Maybe we could have a mix? It's probably good to support native home assistant entity features when possible (for visualizations such as climate cards, services, etc.).

I would suggest to use two select entities that are not part of climate SWING_MODE:
 'UP_DOWN_VANE_CONTROL': 1, 2, 3, 4, 5, 6, Auto
 'LEFT_RIGHT_VANE_CONTROL': 1, 2, 3, 4, 5, Auto, Left, Right

and then map the rest to the SWING_MODE. Would this work?

**Comment by rowysock** [comment]
what do you mean by the "rest"?

What should happen when SWING_HORIZONTAL is selected? Which of the LEFT_RIGHT_VANE_CONTROL options should be sent to the AC?

**Comment by TechHummel** [comment]
In this case: Whatever value the LEFT_RIGHT_VANE_CONTROL select entity has!

```
SWING_OFF:  'UP_DOWN_VANE_CONTROL_OFF': 'Off',  'LEFT_RIGHT_VANE_CONTROL_OFF': 'Off',
SWING_ON:  restore state before SWING_OFF / Default state
SWING_VERTICAL:   UP_DOWN_VANE_CONTROL_SELECT_ENTITY.value,  'LEFT_RIGHT_VANE_CONTROL_OFF': 'Off',
SWING_HORIZONTAL:  'UP_DOWN_VANE_CONTROL_OFF': 'Off', LEFT_RIGHT_VANE_CONTROL_SELECT_ENTITY.value
SWING_BOTH: UP_DOWN_VANE_CONTROL_SELECT_ENTITY.value, LEFT_RIGHT_VANE_CONTROL_SELECT_ENTITY.value
```

**Comment by rowysock** [comment]
What if LEFT_RIGHT_VANE_CONTROL state is 'Off'?

**Comment by tnrclkr** [comment]
Just after last update, new options but "unavailable entity".
![image](https://user-images.githubusercontent.com/48097971/210322862-9c8356c1-6491-4030-8c2a-5071b33fec9b.png)

**Comment by TechHummel** [comment]
> What if LEFT_RIGHT_VANE_CONTROL state is 'Off'?

You are talking about when the AC / HomeWhiz settings are overriding the settings in home assistant? Good question! I would think that you can just store the latest value which is not "Off" (doesn't work for a just started homeassistant, of course).

> * How to store the state befre SWING_OFF

Only update the select entities for values which are not off. It's not perfect, but the best I can think of right now!
