### ISSUE TITLE
Unknown error when adding dishwasher

### ISSUE THREAD

**Issue by Scorpio256** [rowysock/home-assistant-HomeWhiz#74]
Hello, I'm getting an unknown error when trying to add a dishwasher.

Brand: Beko
In-app model: 7622263977
Model: DIN59530AD

![image](https://user-images.githubusercontent.com/7922814/209674422-969eef43-20de-42d5-be73-52d57c9294da.png)

**Comment by rowysock** [comment]
What is your device's "Digital ID"? it can be found in the app device settings

**Comment by Scorpio256** [comment]
Digital ID: F999 9617 3015 5826 7938 28

**Comment by rowysock** [comment]
You should be able to connect to your dishwasher after upgrading to v0.2.3, but there are going to be some specific dishwasher features, that are not yet supported. Please create an issue to add them
