### ISSUE TITLE
Redundant temperature entities select and sensor

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#79]
For my washing machine, there are two redundant entities for temperature - one select and one sensor entity.
![image](https://user-images.githubusercontent.com/15891478/209794268-a5978f15-d91e-43c3-b536-3009b1b12833.png)

**Comment by TheKamakaZi** [comment]
My guess is that the `sensor` provides the current reading, and the `select` allows you to set the desired temperature. Which could mean there may be entities missing, as I'm not picking up a `sensor` for `state` at all.

@rowysock?

**Comment by rowysock** [comment]
@TheKamakaZi yes, my original idea was to leave the temperature as a sensor to provide current reading and keep the nice numeric HA entity with a nice graph history
In reality, a sensor for temperature displays always the same thing as select, so I decided to remove the duplicate sensors in #82

**Comment by TheKamakaZi** [comment]
Thanks for the explanation, @rowysock :)

I do have a concern with this approach, though. When adding `state` from the `select` to my dashboard, it pulls it in as a dropdown (which is obviously default behaviour). However, there doesn't seem to be a clear-cut way to have it render `state` as text in the same manner as a sensor...

...unless I'm missing something blatantly obvious.

**Comment by rowysock** [comment]
We can easily provide both selects and sensors and have them duplicated. @TechHummel what do you think?
