### ISSUE TITLE
Duplicate the select entities as sensor entities

### ISSUE THREAD

**Issue by rowysock** [rowysock/home-assistant-HomeWhiz#84]
> When adding `state` from the `select` to my dashboard, it pulls it in as a dropdown (which is obviously default behaviour). However, there doesn't seem to be a clear-cut way to have it render `state` as text in the same manner as a sensor...
> 
> ...unless I'm missing something blatantly obvious.

_Originally posted by @TheKamakaZi in https://github.com/rowysock/home-assistant-HomeWhiz/issues/79#issuecomment-1366866977_

**Comment by rowysock** [comment]
@TechHummel what do you think about this?

**Comment by TechHummel** [comment]
Good question. I would like to first have a look at ENUM and see how this will fit in!

**Comment by rowysock** [comment]
ENUM entity class from the #37 I think will only display all possible options in the automation, so it's not really related to this issue. I think what @TheKamakaZi wrote about is that most of the time users want to see the info from the washing machine as read-only entities. In the original app, the controls for custom programs are separate from the display of the current state.

The only problem I see is that if we duplicate the sensor and select entities the number of entities for washing machines would be around 40

**Comment by TechHummel** [comment]
Would using the template integration be an option here or is this too complicated?

**Comment by rowysock** [comment]
I came up with one additional argument for duplicating entities: 

If the user changes the value from A to B with the select entity, but the device was unable to change the value. HA will show value B, while the device will report value A. This can happen very easily, as not every state change is possible every time. There are limitations, that are not implemented in the integration (yet?). E.g To change the temperature, the Remote Control has to be enabled.

When I developed the AC integration and the device is located 500km away, having a duplicate sensor and select entities allowed me to verify easily if the select value change was really applied

**Comment by TheKamakaZi** [comment]
Hi @rowysock,

Something just occurred to me in terms of real world usage of washing machines. You set the program up for the load you have, and then pull the trigger.

This makes me think that starting a wash cycle should be, above all else, a service with parameters that's called instead of individual enums, with sensors then reporting current state.

Does that make sense?

**Comment by rowysock** [comment]
Hi @TheKamakaZi 

I like the idea. I thought about it but dismissed it as I thought that HA services are very limited. But now I see that invoking a service from the automation allows specifying all of the parameters with suggestions etc.

Question 1 is: what about devices other than washing machines? AC for example should be controlled by selects and switches.
Question 2: What about the device state? The user should be able to pause the washing machine even when it is running

**Comment by rowysock** [comment]
But there's a problem.

Currently, we create entities dynamically, based on what is present in the config downloaded from the API. Even similar devices can have different configs. For example, my washing machine has different, incompatible options than the @TechHummel washing machine. 

Services require static description in the yaml file: https://developers.home-assistant.io/docs/dev_101_services/#service-descriptions. It's not practically possible to create a service with a static description for each and every device that is supported. We don't even know what devices are supported and what are the possible configurations

**Comment by TheKamakaZi** [comment]
Hey @rowysock 

Thinking about this more and more, I hear you on trying to please everyone. The best possible outcome would have to be based on the lowest common dominator of options between all devices, which would basically nullify what you're trying to accomplish here.

I'm going to do some investigation on how other integrations handle this conundrum, and get back to you. Hopefully, there's a good middle ground to be found.

**Comment by TechHummel** [comment]
Interesting thought for sure! But I also believe this is going to be difficult. My washing machine only supports certain combinations of programs - e.g., an eco cycle does not allow features such as steam - so a good error handling would be required too!

> having a duplicate sensor and select entities allowed me to verify easily if the select value change was really applied

That's a strong argument! Having ~40 entities is not nice, but I don't think this should be a problem as the sensors and select entities are not changing frequently. I'm sure that my temperature sensor with 0.01 °C resolution does generate more data than a homewhiz device. 😄

**Comment by mf1x** [comment]
I'd vote in favour of bringing back the sensor as duplicates. My machine almost only provides select entities. I was about to create sensor templates but if you decide to bring them back I'd really appreciate it :D

**Comment by gabi1324** [comment]
Hi! I just integrated a smart dishwasher into HA. The "select" entity representing the dishwasher's state is a bit strange because it doesn't update on state change. The other select entities need to be duplicated to show the option reported by the machine.  I read this thread earlier and think that at least the state should be a sensor, not a select.

**Comment by TechHummel** [comment]
Thanks for your feedback! This is being worked on right now #100 😄

**Comment by gabi1324** [comment]
> Thanks for your feedback! This is being worked on right now #100 😄

Are there any updates on this issue? I saw that the commit is verified but there is no new update to the integration. Anyway, thanks for the support!

**Comment by TechHummel** [comment]
Not yet! I usually leave merging of branches to @rowysock  but he seems to be busy right now. I also don't think I have the permissions to create a new tag! So I think we need some patience and maybe should consider recruiting a 3rd developer too...

**Comment by rowysock** [comment]
@TechHummel You have my full trust, Tell me what kind of permission you need and where to configure it, to avoid a similar problem of me blocking the progress in the future

**Comment by TechHummel** [comment]
Thanks for that and welcome back 👋 
I can merge pull requests all by myself now, but I am unable to create new tags yet 😢

**Comment by rowysock** [comment]
@TechHummel can you try to create a tag now?

**Comment by TechHummel** [comment]
@rowysock Still doesn't offer me to create tags 😢

**Comment by TechHummel** [comment]
@rowysock I am also not able to merge pull requests by myself. Pull requests need an approval, and I am not able to approve my own pull requests 😞

**Comment by rowysock** [comment]
@TechHummel I've temporarily added my work account as a collaborator in this repo and I had access to create tags and releases. You should be able to create tags and releases too. 

As for the PRs, please just mention me in the comment and I will merge them.

I cannot find how to grant you more permission. I think repositories linked to personal account instead of organizations are very limited in that regard
